### ISSUE TITLE
The terraform docs doesn't show the usage as part of the readme

### ISSUE THREAD

**Issue by abhiyerra** [opszero/terraform-aws-instance#7]
https://github.com/opszero/terraform-aws-bastion/blob/main/usage.md

should be part of the README.md

It no longer shows the readme.

**Comment by thaunghtike-share** [comment]
HI

I don't understand. I found usage.md in the README.md at the end of the fiel such as Tear Down and Usage example. It also updating the input for cloudwatch metric alarm

**Comment by abhiyerra** [comment]
Ah sorry. Found it.
